# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='포스팅 작성자 이름을 입력해주세요.', max_length=20)),
                ('title', models.CharField(max_length=100, validators=[food.models.min_length_3])),
                ('tag', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('food_image', models.URLField()),
                ('res_image', models.URLField()),
                ('opentime', models.TextField()),
                ('menuinfo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
