# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='food_image',
            field=models.URLField(help_text='음식사진 URL을 입력하세요.'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(help_text='도로명 주소를 입력하세요.', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menuinfo',
            field=models.TextField(help_text='메뉴를 입력하세요.'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opentime',
            field=models.TextField(help_text='영업시간을 입력하세요.'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='res_image',
            field=models.URLField(help_text='식당 사진 URL을 입력하세요.'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tag',
            field=models.CharField(help_text='관련 태그를 입력하세요', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='title',
            field=models.CharField(help_text='제목을 3글자 이상 입력하세요', max_length=100, validators=[food.models.min_length_3]),
        ),
    ]
